version: '3'

services:
  apache:
    image: eco-line-system
    container_name: eco-line-system-web
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - 80:80
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      #- ./webapp:/var/www/html
      - ./webapp/app:/var/www/html/app
      - ./webapp/config:/var/www/html/config
      - ./webapp/database:/var/www/html/database
      - ./webapp/public:/var/www/html/public
      - ./webapp/resources:/var/www/html/resources
      - ./webapp/routes:/var/www/html/routes
      - ./docker/apache/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - net1
  db:
    container_name: eco-line-system-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      TZ: 'Asia/Tokyo'
    networks:
      - net1
    ports:
      - 3306:3306
networks:
  net1: